name: simulacao-shp
channels:
  - conda-forge
  - nodefaults  # Impede o Conda de usar o canal 'defaults'
dependencies:
  - python=3.11
  - streamlit=1.36.0
  - geopandas=0.14.4
  - wntr=1.3.0
  - pip